export { default as MenuIcon } from "@material-ui/icons/Menu";
export { default as MenuOpenIcon } from "@material-ui/icons/MenuOpen";
export { default as HomeIcon } from "@material-ui/icons/Home";
export { default as AboutIcon } from "@material-ui/icons/EmojiObjects";
export { default as WorkIcon } from "@material-ui/icons/Work";
export { default as SearchIcon } from "@material-ui/icons/Search";
export { default as FilterIcon } from "@material-ui/icons/FilterList";
export { default as VideoIcon } from "@material-ui/icons/OndemandVideo";
export { default as FlagIcon } from "@material-ui/icons/OutlinedFlag";
export { default as ChevronRightIcon } from "@material-ui/icons/ChevronRight";
export { default as SaveIcon } from "@material-ui/icons/Save";
// export { default as ShareIcon } from "@material-ui/icons/Share";
